bbcarrots/SUSe

package-lock.json, package.json, src/lib/classes/student.ts
- Added necessary private fields
- Added the insertStudent function which calls the insertStudentInfo function and passes itself
Future suggestions:
- Tag DB functions with the keyword "DB" to differentiate from control functions
=> feat: add student entity class

src/lib/stores/CollegePrograms.ts
I added `CollegePrograms.ts` in `stores` so the Registration Form can input the correct college and program when user submits their information.
@allainerain Would this be enough for your dropdowns for the RegForm?
=> feat: add CollegePrograms store for registration form

package-lock.json, src/lib/components/RegisterForm.svelte, src/lib/server/mysql.ts, src/routes/register/+page.svelte
- Edited `src/register/+page.svelte` to forward the form return value to `RegisterForm.svelte` for "No database connection" error.
- Edited `mysql.ts` to return error messages.
=> fix: add form forwarding and error message in State

src/lib/components/Button.svelte, src/lib/components/RegisterForm.svelte
Fixed the RegisterForm.svelte component to have:
- submit field to make the button have the type submit
- post method for the form to submit a post request
=> feat/frontend/register: add form post method and button submit type

src/lib/classes/student.ts, src/lib/server/mysql.ts, src/routes/register/+page.server.ts
- Added the uniqueness checker for the student number and username in the Student class
- Fixed the selectStudentDB query. Tested and verified it works.
All implementations here work as intended.
=> fix/backend/register: add uniqueness checker and fix insert call

src/lib/components/RegisterForm.svelte, src/routes/register/+page.svelte, svelte.config.js
Added the following features:
- CSS error styles when input isn't in the correct format after clicking the submit button
- Remove css-unused-styles error
- Error message for "No database connection" and "Existing sn/username"
- Fixed username to allow numbers as well
=> feat/frontend/register: add error handling for input validation and database errors

src/lib/server/mysql.ts
- Put all the `Error: No database connection` into one try/catch. Also refactored it so that it returns a single variable named `errorNoDBConn`.
- Debugged and replaced AND with OR in selectStudentDB
=> fix: revise error checking and selectStudentDB query

src/routes/register/+page.svelte
Added the confirmation information after successful student registration. Will make it look nicer in a future PR.
=> feat/frontend/register: add confirmation after successful student registration (ugly)

src/lib/server/mysql.ts
- Connection for both student and admin are reset after getting a no database connection error.
- Revised selectStudentDB to select all student records if not given a student number or username argument.
- Added comments and function descriptions in `mysql.ts` for Gab! Happy testing po :>
=> fix/backend/database: fix reconnection, selecting all students, and documentation

src/routes/register/+page.svelte
- Edited the code to show the error message directly instead of processing each individual case
=> fix (register/+page.svelte): display error message directly

src/lib/components/Table.svelte
- Working warning icon for unenrolled students
=> fix(Table.svelte): update field name from 'isenrolled' to 'isEnrolled'

src/lib/components/Sidebar.svelte, src/routes/dashboard/+layout.svelte
- Added basic sidebar for the dashboard!
- Will be updated with the correct styles in the future :D
=> feat: add Navbar.svelte (basic style)

.github/workflows/test.yml, src/index.test.ts, tests/test.ts
Commented out the playwright test case and changed a command on the `test.yml` from `npm test` to `npm run test:unit` so I can approve Allaine's PRs for the UI.
=> fest/frontend: small changes to test files for UI approval

src/lib/components/Table.svelte, src/lib/components/TableHeader.svelte, src/lib/components/TableRow.svelte, src/routes/dashboard/students/+page.svelte
- primary key of the edited field is not added to the payload being dispatched
=> feat: add primaryKeyEdit to dispatch to +page.svelte

src/lib/components/Table.svelte, src/lib/components/TableCell.svelte, src/lib/components/TableRow.svelte, src/routes/dashboard/students/+page.svelte
- Pressing the approve button changes the warning indicator to a greyed out indicator (reloading will reset the UI because the changes aren't connected to the backend yet)
- Pressing approve forwards the primary key to +page.svelte
=> feat/frontend/approve: working approve button in UI

src/lib/components/TableRow.svelte
- Editing now reflects the changes to the frontend (refreshing will revert the changes because they have not yet been reflected in the backend)
=> feat/frontend/edit: reflect edit changes to UI

src/lib/components/Input.svelte, src/lib/components/Sidebar.svelte, src/lib/components/TableCell.svelte, src/lib/components/TableHeader.svelte, src/lib/components/TableRow.svelte, src/lib/utils/types.ts, src/lib/utils/utils.ts, src/routes/dashboard/+layout.svelte, src/routes/dashboard/usage-logs/+page.svelte
Features
- Created input for date time picker
- Adjusted styles to prevent the action buttons from blocking the input fields
- Adjusted style to keep the table header and cell sizes fixed when edit is clicked
=> feat/frontend/usagelogs: create usage log table

src/lib/components/Table.svelte, src/lib/components/TableHeader.svelte, src/lib/components/TableRow.svelte, src/lib/utils/types.ts, src/routes/dashboard/students/+page.svelte, src/routes/dashboard/usage-logs/+page.svelte
Features:
- serviceID is added in the usage logs table
- disableEdit prop is added to add column names which would not be editable
- hide prop is added to add column names which would not be visible in the table
- set up handleUpdate and handleDelete for usage log table
=> feat/frontend/table: add service ID, props for disable editing and hiding columns

src/lib/classes/Student.ts, src/lib/classes/UsageLog.ts, src/lib/server/StudentSB.ts, src/lib/server/UsageLogSB.ts, src/routes/api/student/+server.ts, src/routes/api/usagelog/+server.ts, src/routes/dashboard/students/+page.svelte, src/routes/dashboard/usage-logs/+page.svelte
Connected the Usage Log table UI with the backend. Added some docs.
=> fix/backend/classes: Connected UI and Backend for Usage Log

src/lib/components/Input.svelte, src/lib/components/TableRow.svelte
Regex Patterns for now:
1. First Name: alphabet, space, dash, apostrophes and ñ
2. Middle Initial: 1-2 capital letters
3. Last Name: alphabet, space, dash, apostrophes and ñ
4. Email: alphabet and numbers
5. Student Number: 9 digit number
6. Phone Number: 11 digit number
Added Titles for guided and more transparent warnings.
=> fix(Input.svelte): update regex for pattern validation

src/app.pcss, src/lib/components/Pagination.svelte, src/lib/components/Table.svelte
Currently implemented frontend pagination! We might wanna change this to implement the pagination in the backend instead for larger data but for now, a frontend pagination should work. I'll improve on the UI some time!
=> feat/frontend/pagination: added frontend pagination for tables

src/lib/classes/Student.ts, src/lib/server/StudentSB.ts
- Added the `rfid` property in the StudentFilter data type for implementation of RFID log in.
=> refactor/backend/filter: add rfid as filter in selecting students

src/lib/components/Sidebar.svelte, src/lib/utils/types.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte
This is @gabrielcalubayan72's initial set-up of the service and admin tables. It's currently still using dummy data :D
=> feat/admin/dashboard: setup admin and service tables (no backend)

src/lib/server/StudentSB.ts, src/lib/utils/types.ts, src/routes/dashboard/admin/students/+page.server.ts, src/routes/dashboard/admin/students/+page.svelte
The Student Table in Admin dashboard should now be functioning normally. Refactored some code to make it easier to read. Ready for approval!
=> fix/backend/dashboard/admin/students: Student table fix in new route

src/app.pcss, src/lib/classes/Service.ts, src/lib/components/Button.svelte, src/lib/components/LoginForm.svelte, src/lib/utils/types.ts, src/routes/+page.svelte, src/routes/api/student/+server.ts
Control logic for RFID validation is set up for future input of RFID from Frontend and will return a StudentResponse using a POST request.
=> feat/backend/rfid: add HTTP request handling for RFID validation

src/lib/classes/UsageLog.ts, src/lib/server/UsageLogSB.ts, src/lib/utils/types.ts, src/routes/dashboard/admin/usagelogs/+page.server.ts, src/routes/dashboard/admin/usagelogs/+page.svelte
The UsageLogTable in Admin dashboard should now be functioning normally. Refactored some code to make it easier to read. Ready for approval!
=> fix/backend/dashboard/admin/usagelogs: UsageLog table fix in new route 

src/lib/components/ServiceCard.svelte
@bbcarrots Want to confirm that the image looks good now :D I found out that I accidentally added two conflicting classes which is maybe why it was causing issues with the sizing hehe
=> style/frontend/student/dashboard: adjust image size

src/routes/+page.svelte, src/routes/api/rfid/+server.ts, src/routes/api/student/+server.ts
Move RFID POST request to its own folder `api/rfid`.
=> refactor: relocate POST request for RFID

src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte
connected the admin and service frontend to backend
=> feat: connect admin and service frontend to backend

.gitignore
Just added some lines to .gitignore.
=> feat: deploy to vercel using CLI

deploy-prod.sh
Only `prod` will have a preview and production deployment. (Hopefully)
=> feat: add bash for select deployment

src/lib/classes/Student.ts, src/lib/utils/types.ts, src/routes/dashboard/admin/students/+page.svelte, src/routes/register/+page.server.ts
Added isActive property to Student class. @gabrielcalubayan72 please edit Student tests to account for the changes. Thank you!
=> feat: add isActive property to Student class

src/lib/components/Input.svelte, src/lib/components/TableRow.svelte, src/routes/dashboard/admin/services/+page.svelte
=> fix/dashboard/admin/table: update service table headers and fix editing college bug

src/routes/+page.svelte, src/routes/register/form5/+page.svelte
Just fixed the UI hehe, I kept the button long to keep it consistent with the other pages
=> style: add spacing and center text

src/lib/components/Table.svelte, src/lib/components/TableCell.svelte, src/lib/components/TableHeader.svelte, src/lib/utils/types.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte
=> feat/frontend/admin/dashboard: make unapproved students appear first + add green indicator for active students

src/lib/server/StudentSB.ts, src/routes/api/avail-end/+server.ts, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
Connected the isActive when student avails their first service and ends their last service. Also reflected in the Student table in Admin dashboard.
=> feat: connect isActive when student avails and ends

src/lib/components/RegisterForm.svelte
=> fix: remove password field from register

src/lib/classes/Admin.ts, src/lib/classes/Student.ts, src/lib/server/AdminSB.ts, src/lib/server/ServiceSB.ts, src/lib/server/StudentSB.ts, src/lib/server/UsageLogSB.ts, src/routes/api/avail-end/+server.ts
I rearranged the functions in POST and PATCH requests when Student is availing or ending services so there won't be any updates if `adminID`, `serviceID` or `studentNumber` is absent.
@allainerain Let's talk about this when you're going to implement the UI for when Student avails and ends services!
=> fix/backend/dashboard/student/home: rearrange functions in POST and PATCH requests in avail-end service

src/lib/classes/Admin.ts, src/lib/classes/Student.ts, src/lib/server/AdminSB.ts, src/lib/server/ServiceSB.ts, src/lib/server/StudentSB.ts, src/lib/server/UsageLogSB.ts
@gabrielcalubayan72 Please see changes below
- Added `isEnrolled` and `isActive` filters for Student.
- Fix the `updateStudentDB` to change the `isEnrolled` and `isActive` properties of a Student.
- Cannot delete an active student.
=> fix/backend/dashboard/admin/students: fix update, delete, and filter for Student

src/routes/+page.svelte, src/routes/api/rfid/+server.ts
Added backend for admin login using RFID. Have to connect with UI pa.
The way it works is: we have to click the image in the login page exactly 5 times and then tap the RFID to send a POST request to the Admin table. Else, it will always search the Student table. 
So!  @allainerain could you connect the image that when clicked, it updates the `clicks` variable in the login `+page.svelte` T-T pls and thank you hehe
=> feat: add clicks variable to keep track if admin wants to login

src/lib/components/LoginForm.svelte, src/routes/+page.svelte
@bbcarrots implemented feature where clicking the hero updates the click count :D Here's the other intended behavior
- Switching back and forth from login with RFID and login with username resets the counter
- Clicking it more than 5 times doesn't increment it more (5 is the max)
=> feat/frontend/login: add clicks from image

src/lib/stores/Filters.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte
- Remove need for default min and max or else it will show nothing in the table
- Convert date time string to whatever is used in the backend. The date time filters are currently not functional because of that, I think.
=> feat/frontend/filters: connect frontend filters to backend

src/lib/classes/Admin.ts, src/lib/server/AdminSB.ts, src/lib/server/StudentSB.ts, src/lib/stores/Filters.ts, src/lib/utils/types.ts, src/routes/+page.svelte, src/routes/api/rfid/+server.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
=> fix/backend/filter: fix usage log and student table filter, +admin log in

src/lib/components/Loader.svelte, src/lib/components/ServiceCard.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
Features
- Not shown in the screenshots, but I alphabetically arranged the service cards to prevent shuffling.
=> feat/frontend/student/dashboard: connect student dashboard services to backend, loader

src/lib/components/Sidebar.svelte, src/lib/components/Table.svelte, src/lib/components/TableRow.svelte, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte
- Todo: @bbcarrots connect handleUpdateActive to the backend
- UI will now only update if success response is true
- Please do help me recheck all table operations (prevent unauthorized deletes, make sure edits go through etc)
=> feat/frontend/admin/dashboard: fix pagination, add logout

src/lib/components/TableRow.svelte, src/routes/dashboard/admin/admins/+page.svelte
Wrong branch! But Admin isActive can now be changed from SUSe side! Please review XD
=> fix: connect isActive to backend, works as expected

src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte
I've added a temporary(?) real-time update for the Student, Admin, Usage Log, and Service Table whenever there is an insert, update, or delete in the specific tables in the database.
=> feat/backend/realtime: add realtime updates to Admin tables 

src/lib/classes/Student.ts, src/lib/components/Input.svelte, src/lib/components/Toasts.svelte, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
- Added toasts for success and error status of each of the tables in the admin dashboard.
- Added restrictions for range filters (usage log date range and student number range)
- Input selector for Boolean fields
=> feat/frontend/admin/dashboard: add toasts, filter input validation, boolean input fields

src/routes/api/avail-end/+server.ts, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
Added real-time updates for available services in Student dashboard! 
(Encouraged by the updates done by Allaine to our UI/UX to make it more user friendly and intuitive T-T)
=> feat: add realtime updates to available services in student dashboard

src/lib/stores/Filters.ts, src/lib/stores/SupabaseClient.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte, src/routes/dashboard/student/home/[studentNumber]/+page.svelte
Switching between tables in the Admin dashboard should now be faster. Can someone please test?
=> fix: remove duplicate supabase clients in page.svelte and move to store

src/lib/components/RegisterForm.svelte
I hope this fix works. Added curly braces around the slash.
=> fix: input validation for number fields in register

README.md
- Fix registration input validation error.
- Updated README
=> docs/suse: add docs

package-lock.json
=> feat: page setup

package-lock.json, src/lib/components/TableHeader.svelte, src/lib/server/SupabaseClient.ts, src/lib/utils/filterOptions.ts, src/routes/api/avail-end/+server.ts, src/routes/dashboard/admin/admins/+page.svelte, src/routes/dashboard/admin/services/+page.svelte, src/routes/dashboard/admin/students/+page.svelte, src/routes/dashboard/admin/usagelogs/+page.svelte
- Relocated table headers in the filter file.
- Set default sorting for each table.
=> fix: table sort default

.dockerignore, Dockerfile, package-lock.json, package.json, src/routes/+page.svelte, svelte.config.js
Added code for containerizing SUSe.
=> feat: docker setup

src/lib/components/LoginForm.svelte, src/lib/components/ServiceForm.svelte, src/lib/server/AdminSB.ts, src/lib/server/ServiceSB.ts, src/lib/server/UsageLogSB.ts, src/lib/stores/AdminTables.ts, src/routes/api/avail-end/+server.ts
Created a SUSê instance for EnggLib 1.
=> feat: engglib1-prod branch

src/lib/components/LoginForm.svelte, src/lib/components/ServiceForm.svelte, src/lib/server/AdminSB.ts, src/lib/server/ServiceSB.ts, src/lib/server/UsageLogSB.ts, src/lib/stores/AdminTables.ts, src/routes/api/avail-end/+server.ts
=> Revert "feat: engglib1-prod branch"

src/lib/components/TableCell.svelte, src/lib/utils/filterOptions.ts, src/routes/dashboard/admin/admins/+page.svelte
Removed the admin status column and replaced it with a status icon similar to a student's active status.
=> feat: admin status icon

src/lib/components/Table.svelte, src/lib/components/TableCell.svelte, src/lib/components/TableHeader.svelte, src/lib/utils/filterOptions.ts, src/routes/dashboard/admin/services/+page.svelte
Replaced inUse column status with a status icon similar to the Student table
=> feat: service in use status
